spring:
  config:
    import: "optional:file:.env"
  application:
    name: backoffice-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: ${SERVER_PORT}

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-5.4-mini

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    # ip-address: ${EC2_IP} # 마이크로 서비스 ec2 IP
    register-with-eureka: true
    fetch-registry: true
    deregister-on-shutdown: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Eureka 기반 자동 라우팅 활성화
          lower-case-service-id: true
          include-expression: true     # prefix 제거
          filters:
            - StripPrefix=1     # 자동 라우팅 필터 설정
